module.exports.getTopseller = require('../services/getTopseller.services')
module.exports.getTopBuyer = require('../services/getTopBuyer.services')
module.exports.getTopCreator = require('../services/getTopCreator.services')
module.exports.addTransaction = require('../services/addTransaction.services')
module.exports.salesGraph = require('../services/salesGraph.services')